# Generated by Django 2.1 on 2018-08-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.TextField(help_text='작가 이름이에요.'),
        ),
    ]
