# Generated by Django 2.1 on 2018-08-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
